<?php

/**
 * Created by PhpStorm.
 * User: king
 * Date: 2018/3/6
 * Time: 22:19
 */
namespace app\admin\common;

use think\Controller;
use think\Session;

class Base extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        define('UID',Session::get('user'));
    }
    protected function islogin(){
        if (is_null(UID)){
            $this->error("未登录，无权访问",'login/index');
        }
    }
    protected function alreadylogin(){
        if (!is_null(UID)){
            $this->error("请勿重复登录",'index/index');
        }
    }


}